from enum import Enum, auto


class TokenType(Enum):
    PRINT = auto()
    STRING = auto()
    NUMBER = auto()
    LEFT_PAREN = auto()
    RIGHT_PAREN = auto()
    PLUS = auto()
    MINUS = auto()
    STAR = auto()
    SLASH = auto()
    BANG = auto()
    BANG_EQUAL = auto()
    EQUAL_EQUAL = auto()
    LESS = auto()
    LESS_EQUAL = auto()
    GREATER = auto()
    GREATER_EQUAL = auto()
    AND = auto()
    OR = auto()
    TRUE = auto()
    FALSE = auto()
    SEMICOLON = auto()
    EOF = auto()
